version: '3'
services:
  keycloak:
    image: galiaga/keycloak:0.0.1
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME=localhost
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    ports:
      - "8443:8443"
    command:      
      - start
    networks:
      - red-keycloak
#  keycloak-config-cli:
#    build: .
#    image: adorsys/keycloak-config-cli:latest
#    depends_on:
#      - postgres
#      - keycloak
#    volumes:
#      - ./config:/config
#    environment:
#      keycloak.url : https://keycloak:8443
#      keycloak.user : admin
#      keycloak.password : admin123
#      keycloak.ssl-verify : true 
#      keycloak.availability-check.enabled : true
#      keycloak.availability-check.timeout : 300s
#      keycloak.connect-timeout : 200s
#      spring.profiles.active : json-log
#      import.cache.enabled : false
#    networks:
#      - red-keycloak
  postgres:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-keycloak
networks:
  red-keycloak:
    driver: bridge
volumes:
  postgres_data:
    driver: local